# Update your role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: product-reader-binding
subjects:
- kind: User
  name: "docker-desktop"    # Your current user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: product-reader
  apiGroup: rbac.authorization.k8s.io